services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  webserver:
    build: .
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__DEFAULT_TIMEZONE: America/Bogota
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data_processing:/opt/airflow/data_processing
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: webserver

  scheduler:
    build: .
    depends_on:
      - webserver
      - postgres
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__DEFAULT_TIMEZONE: America/Bogota
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data_processing:/opt/airflow/data_processing
      - ./data:/opt/airflow/data
    command: scheduler

volumes:
  postgres-db-volume:
